/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/naeem4265/custom-controller/pkg/apis/naeem4265.com/v1"
	naeem4265comv1 "github.com/naeem4265/custom-controller/pkg/client/applyconfiguration/naeem4265.com/v1"
	scheme "github.com/naeem4265/custom-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BooksGetter has a method to return a BookInterface.
// A group's client should implement this interface.
type BooksGetter interface {
	Books(namespace string) BookInterface
}

// BookInterface has methods to work with Book resources.
type BookInterface interface {
	Create(ctx context.Context, book *v1.Book, opts metav1.CreateOptions) (*v1.Book, error)
	Update(ctx context.Context, book *v1.Book, opts metav1.UpdateOptions) (*v1.Book, error)
	UpdateStatus(ctx context.Context, book *v1.Book, opts metav1.UpdateOptions) (*v1.Book, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Book, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.BookList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Book, err error)
	Apply(ctx context.Context, book *naeem4265comv1.BookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Book, err error)
	ApplyStatus(ctx context.Context, book *naeem4265comv1.BookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Book, err error)
	BookExpansion
}

// books implements BookInterface
type books struct {
	client rest.Interface
	ns     string
}

// newBooks returns a Books
func newBooks(c *Naeem4265V1Client, namespace string) *books {
	return &books{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the book, and returns the corresponding book object, and an error if there is any.
func (c *books) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Book, err error) {
	result = &v1.Book{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("books").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Books that match those selectors.
func (c *books) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BookList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.BookList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("books").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested books.
func (c *books) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("books").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a book and creates it.  Returns the server's representation of the book, and an error, if there is any.
func (c *books) Create(ctx context.Context, book *v1.Book, opts metav1.CreateOptions) (result *v1.Book, err error) {
	result = &v1.Book{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("books").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(book).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a book and updates it. Returns the server's representation of the book, and an error, if there is any.
func (c *books) Update(ctx context.Context, book *v1.Book, opts metav1.UpdateOptions) (result *v1.Book, err error) {
	result = &v1.Book{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("books").
		Name(book.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(book).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *books) UpdateStatus(ctx context.Context, book *v1.Book, opts metav1.UpdateOptions) (result *v1.Book, err error) {
	result = &v1.Book{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("books").
		Name(book.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(book).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the book and deletes it. Returns an error if one occurs.
func (c *books) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("books").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *books) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("books").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched book.
func (c *books) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Book, err error) {
	result = &v1.Book{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("books").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied book.
func (c *books) Apply(ctx context.Context, book *naeem4265comv1.BookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Book, err error) {
	if book == nil {
		return nil, fmt.Errorf("book provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(book)
	if err != nil {
		return nil, err
	}
	name := book.Name
	if name == nil {
		return nil, fmt.Errorf("book.Name must be provided to Apply")
	}
	result = &v1.Book{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("books").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *books) ApplyStatus(ctx context.Context, book *naeem4265comv1.BookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Book, err error) {
	if book == nil {
		return nil, fmt.Errorf("book provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(book)
	if err != nil {
		return nil, err
	}

	name := book.Name
	if name == nil {
		return nil, fmt.Errorf("book.Name must be provided to Apply")
	}

	result = &v1.Book{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("books").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
