/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/naeem4265/custom-controller/pkg/apis/naeem4265.com/v1"
	naeem4265comv1 "github.com/naeem4265/custom-controller/pkg/client/applyconfiguration/naeem4265.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBooks implements BookInterface
type FakeBooks struct {
	Fake *FakeNaeem4265V1
	ns   string
}

var booksResource = v1.SchemeGroupVersion.WithResource("books")

var booksKind = v1.SchemeGroupVersion.WithKind("Book")

// Get takes name of the book, and returns the corresponding book object, and an error if there is any.
func (c *FakeBooks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Book, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(booksResource, c.ns, name), &v1.Book{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Book), err
}

// List takes label and field selectors, and returns the list of Books that match those selectors.
func (c *FakeBooks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(booksResource, booksKind, c.ns, opts), &v1.BookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.BookList{ListMeta: obj.(*v1.BookList).ListMeta}
	for _, item := range obj.(*v1.BookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested books.
func (c *FakeBooks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(booksResource, c.ns, opts))

}

// Create takes the representation of a book and creates it.  Returns the server's representation of the book, and an error, if there is any.
func (c *FakeBooks) Create(ctx context.Context, book *v1.Book, opts metav1.CreateOptions) (result *v1.Book, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(booksResource, c.ns, book), &v1.Book{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Book), err
}

// Update takes the representation of a book and updates it. Returns the server's representation of the book, and an error, if there is any.
func (c *FakeBooks) Update(ctx context.Context, book *v1.Book, opts metav1.UpdateOptions) (result *v1.Book, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(booksResource, c.ns, book), &v1.Book{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Book), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBooks) UpdateStatus(ctx context.Context, book *v1.Book, opts metav1.UpdateOptions) (*v1.Book, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(booksResource, "status", c.ns, book), &v1.Book{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Book), err
}

// Delete takes name of the book and deletes it. Returns an error if one occurs.
func (c *FakeBooks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(booksResource, c.ns, name, opts), &v1.Book{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBooks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(booksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.BookList{})
	return err
}

// Patch applies the patch and returns the patched book.
func (c *FakeBooks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Book, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(booksResource, c.ns, name, pt, data, subresources...), &v1.Book{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Book), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied book.
func (c *FakeBooks) Apply(ctx context.Context, book *naeem4265comv1.BookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Book, err error) {
	if book == nil {
		return nil, fmt.Errorf("book provided to Apply must not be nil")
	}
	data, err := json.Marshal(book)
	if err != nil {
		return nil, err
	}
	name := book.Name
	if name == nil {
		return nil, fmt.Errorf("book.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(booksResource, c.ns, *name, types.ApplyPatchType, data), &v1.Book{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Book), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBooks) ApplyStatus(ctx context.Context, book *naeem4265comv1.BookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Book, err error) {
	if book == nil {
		return nil, fmt.Errorf("book provided to Apply must not be nil")
	}
	data, err := json.Marshal(book)
	if err != nil {
		return nil, err
	}
	name := book.Name
	if name == nil {
		return nil, fmt.Errorf("book.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(booksResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.Book{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Book), err
}
